sudo: required

language: node

services:
  - docker

before_install:
  - docker build -t $(cat NAME) .

script:
  - docker run --rm --volume $(pwd)/tests:/tests $(cat NAME) /bin/bash /tests/travis-sample-app.sh
